# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13z5PbRnzrlb8KRda3i52B__NzbnSQZVJ
"""

# app_bidirectional_sign_streamlit.py

import streamlit as st
import numpy as np
from tensorflow.keras.models import load_model
from rembg import remove
from PIL import Image
from gtts import gTTS
import os
import json
import io
import re

# ------------ CONFIG ------------
MODEL_PATH = "Mobile_98.keras"
CLASS_LABELS_PATH = "class_labels.json"
PLACEHOLDER_IMAGE = r"C:\Users\Gobi\Desktop\miniproject\BGremoved_clean_images\not sign.png"
# --------------------------------

# Load model and labels
model = load_model(MODEL_PATH)
with open(CLASS_LABELS_PATH, "r", encoding="utf-8") as f:
    class_labels = json.load(f)
class_labels = {int(k): v.strip() for k, v in class_labels.items()}

# Malayalam → Tamil
MALAYALAM_TO_TAMIL_MAP = {
    "class_1  അ - A": "அ",
    "class_2  ആ - AA": "ஆ",
    "class_3  ഇ -  I": "இ",
    "class_4  ഈ - II": "ஈ",
    "class_5  ഉ - U": "உ",
    "class_6  ഊ - UU": "ஊ",
    "class_8  എ - E": "எ",
    "class_9  ഏ -  EE": "ஏ",
    "class_10  ഐ - AI": "ஐ",
    "class_11  ഒ - O": "ஒ",
    "class_12  ഓ - OO": "ஓ",
    "class_13  ഔ - AU": "ஔ",
}

# Tamil → Malayalam
TAMIL_TO_MALAYALAM_MAP = {
    "class_1  அ": "അ",
    "class_2  ஆ": "ആ",
    "class_3  இ": "ഇ",
    "class_4  ஈ": "ഈ",
    "class_5  உ": "ഉ",
    "class_6  ஊ": "ഊ",
    "class_7  எ": "എ",
    "class_8  ஏ": "ഏ",
    "class_9  ஐ": "ഐ",
    "class_10  ஒ": "ഒ",
    "class_11  ஓ": "ഓ",
    "class_12  ஔ": "ഔ",
    "class_13  ஃ": "അഃ",
}

# Reference images (simplified)
reference_images = {
    "class_1 അ - A": r"C:\Users\Gobi\Desktop\miniproject\BGremoved_clean_images\Tamil_class_01\frame_0001.jpg",
    "class_2 ആ - AA": r"C:\Users\Gobi\Desktop\miniproject\BGremoved_clean_images\Tamil_class_02\frame_0001.jpg",
    "class_1  அ": r"C:\Users\Gobi\Desktop\miniproject\BGremoved_clean_images\Malayalam_class_01\frame_0001.jpg",
    "class_2  ஆ": r"C:\Users\Gobi\Desktop\miniproject\BGremoved_clean_images\Malayalam_class_02\frame_0001.jpg",
}

# ---------------- Utility Functions ----------------
def normalize_label(label):
    return re.sub(r'\s+', ' ', label.strip().lower())

def composite_on_black(pil_img):
    """Add black background to transparent image."""
    if pil_img.mode in ("RGBA", "LA") or ("transparency" in pil_img.info):
        bg = Image.new("RGB", pil_img.size, (0, 0, 0))
        bg.paste(pil_img, mask=pil_img.split()[-1])
        return bg
    return pil_img.convert("RGB")

def preprocess_for_model(pil_img, target_size=(128, 128)):
    img_resized = pil_img.resize(target_size)
    arr = np.array(img_resized).astype("float32") / 255.0
    if arr.ndim == 2:
        arr = np.stack([arr]*3, axis=-1)
    return np.expand_dims(arr, axis=0)

def get_translated_sign_name(raw_label: str):
    raw_label = raw_label.strip()
    if raw_label in MALAYALAM_TO_TAMIL_MAP:
        return MALAYALAM_TO_TAMIL_MAP[raw_label], "Malayalam → Tamil"
    elif raw_label in TAMIL_TO_MALAYALAM_MAP:
        return TAMIL_TO_MALAYALAM_MAP[raw_label], "Tamil → Malayalam"
    else:
        return "?", "Unknown"

# ---------------- Streamlit App ----------------
st.set_page_config(page_title="Bidirectional Sign Recognition", layout="centered")
st.title("🤟 Tamil ↔ Malayalam Sign Language Recognition with Voice Output")

uploaded_file = st.file_uploader("Upload a Sign Image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    st.image(uploaded_file, caption="Uploaded Image", use_column_width=True)

    # Process uploaded image
    img = Image.open(uploaded_file).convert("RGB")
    no_bg = remove(img)
    cleaned_rgb = composite_on_black(no_bg)

    # Prediction
    x = preprocess_for_model(cleaned_rgb)
    preds = model.predict(x)
    pred_idx = int(np.argmax(preds, axis=1)[0])
    confidence = float(np.max(preds))
    pred_label = class_labels.get(pred_idx, f"class_{pred_idx}")

    # Translation
    translated_name, translation_dir = get_translated_sign_name(pred_label)

    # Voice
    tts_path = "translated_voice.mp3"
    if re.search(r'[\u0D00-\u0D7F]', translated_name):
        tts = gTTS(text=translated_name, lang="ml")
    else:
        tts = gTTS(text=translated_name, lang="ta")
    tts.save(tts_path)

    # Reference image
    ref_path = PLACEHOLDER_IMAGE
    normalized = normalize_label(pred_label)
    for key, path in reference_images.items():
        if normalize_label(key) == normalized and os.path.exists(path):
            ref_path = path
            break

    # Show results
    st.subheader("📊 Prediction Results")
    st.write(f"**Predicted Class:** {pred_label}")
    st.write(f"**Confidence:** {confidence:.4f}")
    st.write(f"**Translation Direction:** {translation_dir}")
    st.write(f"**Translated Letter:** {translated_name}")

    col1, col2 = st.columns(2)
    with col1:
        st.image(cleaned_rgb, caption="Background Removed (Black BG)")
    with col2:
        st.image(ref_path, caption="Reference Image")

    st.audio(tts_path, format="audio/mp3")

else:
    st.info("Please upload an image to start recognition.")